[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"
solc = ".tools/solc.exe"
evm_version = "istanbul"
fs_permissions = [{ access = "write", path = "./data/phase0" }, { access = "write", path = "./data/phase1" }, { access = "write", path = "./data/phase3" }]

[profile.botchain]
src = "src"
test = "test"
out = "out-botchain"
cache_path = "out-botchain/cache"
broadcast = "out-botchain/broadcast"
solc = ".tools/solc.exe"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
